// Generated by Wrangler by running `wrangler types`

interface Env {
	AZURE_OPENAI_ENDPOINT: "https://REPLACE-ME.openai.azure.com";
	AZURE_OPENAI_DEPLOYMENT: "gpt-4o-mini";
	AZURE_OPENAI_API_VERSION: "2024-10-21";
	ASSETS: Fetcher;
}
